// <auto-generated />
namespace EFORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Northwind11Schema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Northwind11Schema));
        
        string IMigrationMetadata.Id
        {
            get { return "201712041358377_Northwind1.1 Schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
